version: "3.7"

services:
  jenkins:
    image: sixeyed/jenkins:bday7
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - infrastructure

networks:
  infrastructure:
    name: build-infrastructure